Don't update panel history if the panel is armed
mag1024/bosch-alarm-mode2 pull request #15
Opened 2023-09-03 00:22 UTC by sanjay900

Better fix for https://github.com/mag1024/bosch-alarm-homeassistant/issues/10

2023-09-03 00:23 UTC, sanjay900 commented
just catching the exception means we will flood users logs, while it would be better to just not support retriving history  when the panel is not armed.

2023-09-03 01:02 UTC, mag1024 requested changes

2023-09-03 01:02 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        if area_status==AREA_STATUS.DISARMED:
Spaces around ==, please. Alternatively, we could not check at all -- we're already relying on _load_history to check if _all_ areas are now disarmed.

2023-09-03 01:02 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        if area_status==AREA_STATUS.DISARMED:
Please add a comment that this is necessary because the initial history load may have been skipped if some areas were armed during initialization.

2023-09-03 03:44 UTC, merged

2023-09-03 03:45 UTC, mag1024 commented
Thank you!

2023-09-10 02:48 UTC, sanjay900 commented
@mag1024 did you end up releasing another version of the home assistant integration with these changes?

2023-09-12 16:49 UTC, mag1024 commented
Nope, I have not. I can try to do it later in the week -- or if you get to it sooner, please feel free.