Add support for solution 3000 + polling, and for the alarm being triggered
mag1024/bosch-alarm-mode2 pull request #2
Opened 2023-05-21 21:17 UTC by sanjay900

This also checks for support of some commands, namely the `PRODUCT_SERIAL` command as this isn't supported on a lot of panels by the looks of things.

2023-05-21 21:18 UTC, sanjay900 commented
We will probably want to work out a nicer way to handle the platform specific stuff as I am currently just using if statements here, and you did say you preference would be to not do that, but im not really sure what a better method is.

2023-05-22 05:09 UTC, mag1024 reviewed
Oh wow, you've made lots of progress!
Overall, looks good -- just a few comments aiming to clean up the structure a bit.
I'm really happy to see that the polling can just use the loading code and doesn't add a lot of cruft.

Will try to test it on my panel soon.

Thank you again!

2023-05-22 05:09 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        if self.model in ["Solution 2000", "Solution 3000"]:
Yeah, the ifs are a bit awkward... Maybe longer term we can think about some kind of a panel-model-specific adaptor that can encapsulate all the stuff that's different per-panel, but for now, let's at least break it up into multiple methods, so we can write something like:

if self.model in ["Solution 2000", "Solution 3000"]:
  self._login_remote_user(...)
else:
  self._authenticate_automation(...)

2023-05-22 05:09 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +            while True:
Ditto, let's break these out into helper methods

2023-05-22 06:07 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +        self.point_count = 0
I use these values when populating the entity lists, hence the capacities stuff

2023-05-22 06:07 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +        self._featureProtocol01 = False
We likely don't need most of these, I had just copy pasted aist from elsewhere and was planning on pruning it down once we have everything we need working

2023-05-22 06:08 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +        return (self.is_part_armed() or self.is_all_armed()) and ALARM_MEMORY_PRIORITY_BURGLARY_ALARM in self.alarms
Good point, I'll add that in

2023-05-22 06:09 UTC, sanjay900 commented on bin/alarm.py
> +panel = Panel(host=args.host, port=args.port, passcode=args.passcode, legacymode=False)
It's only really there if someone is on such an old firmware, that their firmware doesn't support the commands for deriving, though in saying that, maybe instead we just catch the nak from that and jump into a legacy mode that way

2023-05-22 07:11 UTC, sanjay900 commented on bin/alarm.py
> +panel = Panel(host=args.host, port=args.port, passcode=args.passcode, legacymode=False)
thinking about it now, i think those old panels will just not return any data for what is supported, so we will automatically fall back to the older formats in those cases

2023-05-22 07:13 UTC, sanjay900 commented
I was also very glad when the loading code just worked

2023-05-22 10:31 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +        self.point_count = 0
Okay i thought that was necessary, but it turns out it isn't, which is good as some panels dont support the capacities commands anyways. I've now removed it and _load_capacities

2023-05-22 11:40 UTC, EHylands commented on bin/alarm.py
> +panel = Panel(host=args.host, port=args.port, passcode=args.passcode, legacymode=False)
Hi @sanjay900 , always happy to follow up on other projects progress!

With WhatAreYou command format 3, LegacyMode is not as useful on Solution Panel, B Series panel and newer G panels.

On my side, I mostly kept LegacyMode around for older GV4 panels or Amax panels. Only one user tried running it on GV4, but it failed because he was running firmware < 2.0 and didn't want to risk an upgrade.

2023-05-22 11:45 UTC, sanjay900 commented on bin/alarm.py
> +panel = Panel(host=args.host, port=args.port, passcode=args.passcode, legacymode=False)
I see, it would be nice to support those older panels. What exactly is the failure you get when you use command format 3?

2023-05-22 11:51 UTC, sanjay900 commented
For the moment ive pushed the package to pypi just so that i can get people testing a version without needing them to go and manually delete their local git copies when i make changes. I had someone test on the solution 2000 and it is working there, and im currently getting someone to also test on a AMAX300 as well

2023-05-22 11:54 UTC, EHylands commented on bin/alarm.py
> +panel = Panel(host=args.host, port=args.port, passcode=args.passcode, legacymode=False)
As of now, no user reported success or error for these older panels ...

WhatAreYou CF 3 is IIP 5.72, so maybe not supported by older panels or firmware.

With Home Assistant bigger user base, you will probably get request for those panels !

I mostly use LegacyMode now to test the pooling code on my B panel.

2023-05-22 11:56 UTC, sanjay900 commented on bin/alarm.py
> +panel = Panel(host=args.host, port=args.port, passcode=args.passcode, legacymode=False)
Ah okay, thank you!

2023-05-23 16:41 UTC, mag1024 commented on bosch_alarm_mode2/const.py
> +PANEL_AREAS_MAX = {
Do we know what panels this is actually necessary for?

In general, to make reviewing easier, I would suggest the approach of focusing this PR on support for the panels we have access to/can directly test with, and splitting additional panel compatibility features into separate PR.

2023-05-23 19:59 UTC, sanjay900 commented
Yeah, I'm testing with someone's Amax 3000 at the moment

On Wed, 24 May 2023, 4:41 am Michael Grigoriev, ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In bosch_alarm_mode2/const.py
> <https://github.com/mag1024/bosch-alarm-mode2/pull/2#discussion_r1202692610>
> :
>
> > @@ -61,6 +61,39 @@
>      0xA9: "B6512 (US1B)",
>  }
>
> +PANEL_AREAS_MAX = {
>
> Do we know what panels this is actually necessary for?
>
> In general, to make reviewing easier, I would suggest the approach of
> focusing this PR on support for the panels we have access to/can directly
> test with, and splitting additional panel compatibility features into
> separate PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mag1024/bosch-alarm-mode2/pull/2#pullrequestreview-1440175687>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOGYQHUIII2WD6YX2FMMUDXHTSCTANCNFSM6AAAAAAYJUFZFA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-23 23:25 UTC, sanjay900 commented on bosch_alarm_mode2/const.py
> +PANEL_AREAS_MAX = {
Currently testing with someone elses AMAX panel, but i was really just trying to see if it would be easy enough to get going without changing too much - though now its starting to look like the answer to that is no, and the AMAX panel is just a bit odd in how it works unfortunately. I will see though, i might be able to get direct access to one.

2023-05-24 03:56 UTC, mag1024 commented on bosch_alarm_mode2/const.py
> +PANEL_AREAS_MAX = {
Cool -- but I would suggest doing this kind of exploration on a separate branch so that it's easy to keep track of what's changed, especially in case it doesn't work out. In parallel we can work on addressing the remaining cleanups in this PR to get it merged.

2023-05-24 04:44 UTC, sanjay900 commented on bosch_alarm_mode2/const.py
> +PANEL_AREAS_MAX = {
yeah fair enough, i was hoping it would just work but since it doesnt, ill just slice all these commits off

2023-05-24 04:51 UTC, sanjay900 commented on bosch_alarm_mode2/const.py
> +PANEL_AREAS_MAX = {
Have now cleaned all this up

2023-05-24 04:52 UTC, sanjay900 commented
@mag1024 does this all work on your panel?

2023-05-25 02:38 UTC, mag1024 requested changes
Apologies for the delay, my HA dev environment has bit-rotted, and I had to re-create it.
Tested it with my panel, and everything seems to still work.

Overall, looks great!
The main comment is about unifying _model and _basicinfo -- everything else is mostly nitpicks.
And thanks again :))

2023-05-25 02:38 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        data = await self._connection.send_command(CMD.WHAT_ARE_YOU, commandformat)
can inline command command format as 'b\x03'

2023-05-25 02:38 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +    async def _model(self):
Do we need both flavors of WHAT_ARE_YOU?
Can we unify _model and  _basicinfo, and always send format 3?

2023-05-25 02:38 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        return names
nit: line break between functions

2023-05-25 02:38 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +    async def _load_configured_names(self, config_cmd, type):
I think this is a bit mis-named, because it doesn't actually load any *names*.
Maybe something like
_load_configured_entities(self, load_cmd, entity_type) -> dict[int, str]:

2023-05-25 02:38 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +                print(f"Found unknown area {area}, supported areas: [{self.areas.keys()}]")
Log.warning

2023-05-25 02:38 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +                # If events have been cleared, then we can just clear all areas instead of asking the panel for more info
line wrap, please

2023-05-25 04:09 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        if self.model in ["Solution 2000", "Solution 3000"]:
BTW, have you tested what happens if we send an AUTHENTICATE to a solutions panel?
Does it reject it as an error, or does it get confused and hang?
If it's the former, maybe we can just blinding try both authentication methods in order all the time without conditioning this on the model and succeed if either succeeds. This would remove the dependency between authenticate and basicinfo.

2023-05-25 08:03 UTC, sanjay900 commented
One other thing, since not every panel has a serial number, should we be using something else for the unique id?

2023-05-25 12:32 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +        if self.model in ["Solution 2000", "Solution 3000"]:
have just changed it now so that it just does both methods

2023-05-25 12:34 UTC, sanjay900 commented
Im sure theres a better way to handle history - i think tomorrow ill add in checking if the text based history commands are supported for a panel, and ill use that if its available - i know the solution and amax panels dont support it though.
We might also want to look at a more standardized history format, and im not sure if theres a better way to bring that data across to home assistant besides just a giant string in an attribute

2023-05-25 18:55 UTC, mag1024 commented
The history stuff looks cool, but following the best practice of keeping the changes small/focused, let's please pull it out into a separate PR.

Re: missing serial numbers. I guess we the best we can do at that point is the model? We just need something that is stable and "unique enough" not to have collisions within a given HA instance.

2023-05-25 21:27 UTC, sanjay900 commented
Fair call, ill splice out the history stuff into its own branch. I was just trying to get something that had the features of my old project, so I can just deprecate that and push people over to this one.

2023-05-25 21:36 UTC, sanjay900 commented
Out of curiousity though, does that history stuff parse correctly on your panel?

2023-05-26 04:01 UTC, mag1024 commented
> Out of curiousity though, does that history stuff parse correctly on your panel?

This is what I got:

```
2023-05-25 23:59:19.825 DEBUG (MainThread) [custom_components.bosch_alarm.bosch_alarm_mode2.panel] Loading history...
2023-05-25 23:59:19.825 DEBUG (MainThread) [custom_components.bosch_alarm.bosch_alarm_mode2.connection] >> b'\x01\x06\x15\xff\x00\x00\x00\x00'
2023-05-25 23:59:20.411 DEBUG (MainThread) [custom_components.bosch_alarm.bosch_alarm_mode2.connection] << b'\x01\xde\xfe\t\x00\x00\x0b\x87\x00\x19\x00\x00\x00\x14\x00\x00\x00\x00-\x16\xd9@\x06fffffffff\x000\x00\x00\x00\x00\x00\x00\x00\x00-\x19G\xc0ffffffffff\x00\r\x00\x00\x00\x15\x00\x00\x00\x00-\x19G\xc0\x06fffffffff\x00y\x00\x00\x00\x00\xff\xff\x00\x04-\x19H\x00ffffffffff\x00=\x00\x00\x00\x00\x00\x01\x00\x03-\x1ai\x80ffffffffff\x000\x00\x00\x00\x00\x00\x00\x00\x00-\x1bU@ffffffffff\x00\r\x00\x00\x00\x15\x00\x00\x00\x00-\x1bU@\x06fffffffff\x00y\x00\x00\x00\x00\xff\xff\x00\x04-\x1bU\x80ffffffffff\x00\x13\x00\x00\x00\x04\x00\x00\x00\x00-\x1ci\x00\x06fffffffff'
2023-05-25 23:59:20.411 DEBUG (MainThread) [custom_components.bosch_alarm.bosch_alarm_mode2.panel] Loading count: 9
2023-05-25 23:59:20.411 ERROR (MainThread) [root] Initial panel connection failed
Traceback (most recent call last):
File "/home/mag/homeassistant/core/config/custom_components/bosch_alarm/__init__.py", line 38, in async_setup_entry
await panel.connect(load_selector=bosch_alarm_mode2.Panel.LOAD_ALL_HISTORY)
File "/home/mag/homeassistant/core/config/custom_components/bosch_alarm/bosch_alarm_mode2/panel.py", line 165, in connect
await self._connect(load_selector)
File "/home/mag/homeassistant/core/config/custom_components/bosch_alarm/bosch_alarm_mode2/panel.py", line 241, in _connect
await self.load(load_selector)
File "/home/mag/homeassistant/core/config/custom_components/bosch_alarm/bosch_alarm_mode2/panel.py", line 175, in load
await self._load_history()
File "/home/mag/homeassistant/core/config/custom_components/bosch_alarm/bosch_alarm_mode2/panel.py", line 270, in _load_history
area._add_history(self._history_parser(data))
File "/home/mag/homeassistant/core/config/custom_components/bosch_alarm/bosch_alarm_mode2/history.py", line 735, in _parse
return b_g_history(date, event_code, area, param1, param2, param3)
TypeError: b_g_history() takes 5 positional arguments but 6 were given
```

2023-05-26 04:30 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        self._supportsSubscriptions = False
Let's rename these to lower case with underscores for consistency

2023-05-26 04:30 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +                self._poll_task = loop.create_task(self._poll())
Actually, we might still have an issue here.
load() gets called from _connect(), which can get called repeatedly from connection monitoring without ever calling disconnect()
This probably means that we need to do the task cleanup either in _on_disconnect(), or avoid re-creating the task in load() if it's already running. The former is probably more correct, as otherwise it will probably spam failure messages during the disconnected state.

2023-05-26 04:30 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        creds = int(str(self._passcode).ljust(8, "F"), 16)
The int conversion throws if the passcode is not numeric
If the RSC passcode must always numeric, and the passcode we were given isn't that a strong indication that it's actually an automation passcode, and we don't even need to attempt this fallback.

2023-05-26 04:30 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        self._featureCommandRequestAreaTextCF01 = (bitmask[7] & 0x20) != 0
Did we forget to initialize this in the constructor?

2023-05-26 07:40 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +        creds = int(str(self._passcode).ljust(8, "F"), 16)
ah yeah true, did not realise you could use non numeric passcodes in the standard auth

2023-05-26 07:56 UTC, sanjay900 commented
Ive just sliced the history stuff off into another branch

2023-05-27 04:22 UTC, mag1024 requested changes
Ok, hopefully the last round of comments!
Thanks for your patience!

2023-05-27 04:22 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +                self._connection.close()
I think this isn't quite right, because we won't do the close if the AUTHENTICATE returns 0x02.

2023-05-27 04:22 UTC, mag1024 commented on bosch_alarm_mode2/connection.py
> +        loop.create_task(self._on_disconnect())
I think asyncio.create_task is the new preferred way of spawning coros.

But AFAIU, there's no point in spawning a task that we don't await, just to await another task's return.
We should probably keep _on_disconnect() sync, and just do self._poll_task.cancel() without awating.

2023-05-27 04:22 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +            loop.create_task(self._get_alarms_for_priority(priority))
ditto re: using asyncio.create_task

2023-05-27 04:42 UTC, sanjay900 commented on bosch_alarm_mode2/connection.py
> +        loop.create_task(self._on_disconnect())
yeah i wasn't sure if cancelling it like that would cause any problems

2023-05-27 04:44 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +                self._connection.close()
ah yeah, ill just remove that extra if, i missed that

2023-05-27 04:51 UTC, sanjay900 commented
Before we merge this, have you got a pypi account so i can transfer that across to you?

2023-05-28 03:57 UTC, mag1024 approved these changes
Look great! Thanks for all fixes!
Just created a pypi account under the same username as my github: mag1024

2023-05-28 03:57 UTC, merged