Check commands for compatibility before using them
mag1024/bosch-alarm-mode2 pull request #24
Opened 2023-10-20 21:26 UTC by sanjay900

AMAX panels don't support `Request output text` and more strangely, they don't support alarm memory summary CF01 but do support CF02.

2023-10-21 01:07 UTC, mag1024 requested changes

2023-10-21 01:07 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +            self._supports_command_request_output_text_cf01,
The number of bools at the top level is getting a bit out of control :)

How about we turn all the parameters to load_names into a tuple, store them as member variables, and update the "supports" directly in them?

So instead of `self._supports_command_request_point_text_cf01 = bitmask[11] & 0x80` it'll become `self._load_points_spec.supports_cf01 = bitmask[11] & 0x80`

And _load_points() will become just `await self._load_names(self._load_points_spec)`

Or, alternatively/additionally, we can have turn the supported formats into a set, so one can write `1 in point_text_supported_formats`

2023-10-21 01:36 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +            self._supports_command_request_output_text_cf01,
thinking about it now, we don't even need to go as extreme as a tuple. We can just store the highest supported command, and then compare with that.

2023-10-21 01:43 UTC, sanjay900 commented
Is there a more pythonic way to write these sections?
```python
 if bitmask[7] & 0x08:
      self._area_text_supported_format = 3
 elif bitmask[7] & 0x20:
      self._area_text_supported_format = 1
  ```

2023-10-21 04:26 UTC, mag1024 requested changes

2023-10-21 04:26 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +            self._area_text_supported_format = 3
You could do a nested ternary (x if c else y), but for the sake of readability perhaps a helper function is the way to go

2023-10-21 04:26 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        if supported_format==3:
here and below: spaces around ==, please

2023-10-21 04:26 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        format = None
Consider:

```
if not self._alarm_summary_supported_format:
  return
format = bytearray([0x02] if self._alarm_summary_supported_format == 2 else [])
```

2023-10-21 04:26 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        self._area_text_supported_format = 0
Nice, I like this approach a lot!

In the future maybe we can still add some better organization by introducing a helper class named something like PanelFeatures, and moving all these members, as well as the logic for populating them there.

2023-10-21 09:04 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +        self._area_text_supported_format = 0
Yeah for sure that would make sense if we had more of these

2023-10-23 00:41 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +            self._area_text_supported_format = 3
The function I was thinking of would be something like
`self._area_text_supported_format = _supported_format(bitmask[7], [(0x08, 3), (0x20, 1)])

2023-10-23 04:57 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +    def _supported_format(self, value, masks):
Doesn't have to be be a member of Panel -- let's move it out

2023-10-23 04:57 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        self._area_text_supported_format = self._supported_format(bitmask[7], ((0x08, 3), (0x20, 1)))
not sure if it makes a practical difference, but I think a list would make more sense than a tuple for the outer container

2023-10-23 04:57 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +
nit: extraneous spaces

2023-10-23 19:00 UTC, merged

2023-10-23 19:00 UTC, mag1024 commented
Thank you!