Implement auth for AMAX panels
mag1024/bosch-alarm-mode2 pull request #25
Opened 2023-10-20 21:29 UTC by sanjay900

The AMAX panels require both an automation code based auth and a remote user based auth. This means we need to support passing in data for both types of auth.

2023-10-20 21:30 UTC, sanjay900 commented
From a home assistant end we will need to change the config format, and it would be best to migrate any currently stored codes to both variables where it makes sense, so that solution users don't need to reconfigure their integrations.

2023-10-20 23:41 UTC, sanjay900 commented
Looking into some solution stuff, it may pay to require both for solution panels as well, as it appears the only way to sort the output problems for the solution panels will be to read and parse the configuration from the panel, which requires being logged in with both codes.

2023-10-21 00:52 UTC, mag1024 requested changes

2023-10-21 00:52 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        self._supports_remote_user = data[0] <= 0x24
If we're going to have bools, they should probably be intialized in __init__ -- but maybe we can null out the passcode/automation_code as appropriate instead, and avoid the bools altogether?

2023-10-21 01:17 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +        self._supports_remote_user = data[0] <= 0x24
Seems reasonable, i will just require both codes for the solution panels as well, so i will just null out the user code on b/g series panels.

2023-10-21 01:40 UTC, sanjay900 commented
One thing to note is that this will change authentication for solution panels as well, but that just means we need to make sure we warn users about that when they get the update.

2023-10-21 04:07 UTC, mag1024 commented on README.md
> +- For Solution and AMAX panels, use both your automation code and your installer code for authentication.
So "installer" is the like root user of the panel?
Would another user's code theoretically work here -- possibly only showing the entities the user has permission for?
I'm trying to confirm the terminology, because if it's actually the case that the _installer_ code is required, we should probably rename the `passcode` member/arugment in the Panel to `installer_code`

2023-10-21 04:07 UTC, mag1024 commented on bin/alarm.py
> +cli_parser.add_argument('-U', '--installercode', help="Installer code")
posix flag naming convention would suggest --installer-code; but this is conditional on the answer to the question above

2023-10-21 06:18 UTC, sanjay900 commented on README.md
> +- For Solution and AMAX panels, use both your automation code and your installer code for authentication.
Sadly for the solution panels and amax panels it does need to be an installer code

2023-10-21 06:20 UTC, sanjay900 commented on README.md
> +- For Solution and AMAX panels, use both your automation code and your installer code for authentication.
Non installer codes won't give access to the commands we need for the solution panel, and non installer codes don't seem to work on the amax panels

2023-10-21 06:21 UTC, sanjay900 commented on bin/alarm.py
> +cli_parser.add_argument('-U', '--installercode', help="Installer code")
Makes sense, I'll change that

2023-10-23 04:53 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +    def __init__(self, host, port, installer_code, automation_code):
nit: let's put `automation_code`, as the non-optional parameter, before the optional `installer_code`

2023-10-23 04:53 UTC, mag1024 commented on bin/alarm.py
>  cli_parser.add_argument('-P', '--passcode', help="Automation passcode")
For full consistency let's also rename this to --automation-code

2023-10-23 04:53 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
>              self._output_subscription_start_index = 6
Should we be checking that the _installer_code is non-empty on this branch?

2023-10-23 18:31 UTC, merged