Add support for history
mag1024/bosch-alarm-mode2 pull request #3
Opened 2023-05-26 10:56 UTC by sanjay900

Builds on #2
We use the raw history command as solution and amax panels don't allow using the text events command. This also means we can come up with our own scheme for events as well, though for the moment i have just copied descriptions straight from the documentation.

2023-05-28 04:34 UTC, sanjay900 commented
@mag1024 Out of curiosity, is this working on your panel now? I fixed that error you encountered the other day

2023-05-29 02:44 UTC, mag1024 requested changes

2023-05-29 02:44 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +    async def area_disarm(self, area_id, code):
Merge error?

2023-05-29 02:44 UTC, mag1024 commented on bosch_alarm_mode2/const.py
> +    REQUEST_RAW_HISTORY_EVENTS = 0x15
My docs say that 0x15 is deprecated, and 0x63 should be used instead.
There's also, apparently, a version that's supposed to directly return human-readable output (0x16). Have you looked into either of these?

2023-05-29 02:44 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +                data = data[self._history_len:]
Is see that this is the only use of history len... why do we need to trim it to a different number of events depending on the panel model?

2023-05-29 02:44 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        self._history = []
What do you think of pushing all this state into the History object -- instead of just making a dumb parser?

2023-05-29 02:44 UTC, mag1024 commented on bosch_alarm_mode2/history.py
> +def _get_int16(data, offset=0):
This is a copy of functions already in Panel, right? Let's find a way to share them. Maybe pull them into a util.py?

2023-05-29 02:44 UTC, mag1024 commented on bosch_alarm_mode2/history.py
> +        user = "Installer"
Use a dict?

2023-05-29 02:44 UTC, mag1024 commented on bosch_alarm_mode2/history.py
> +def solution_history(date, id, param1, param2):
local-only helpers should begin with an _

2023-05-29 02:44 UTC, mag1024 commented on bosch_alarm_mode2/history.py
> +    # Amax requires different strings depending on param1 sometimes
Oh, wow, this is nasty! Is Amax their oldest panel? Maybe that's why the protocol is so hacked up.

It seems that we're always doing the same action at the end of the day....
I think we can make this simpler by pulling out a helper function decide on a key

def _amax_history_key(id, param1) -> string:
  return id if id in AMAX_HISTORY_FORMAT
  return f"{id}_{param1}" if f"{id}_{param1}" in AMAX_HISTORY_FORMAT
  ...

def amax_history(date, id, param1, param2):
  ...
  key = _amax_history_key(id, param1)
  return date + AMAX_HISTORY_FORMAT[key].format(param1=param1, param2=param2)

2023-05-29 02:44 UTC, mag1024 commented on bosch_alarm_mode2/history.py
> +def history_parser(panel):
CamelCase, please

2023-05-29 02:44 UTC, mag1024 commented on bosch_alarm_mode2/history.py
> +        if panel <= 0x24:
What do you think of creating 3 top separate parsers per model type, and statically creating the right one for the panel we're talking to?

2023-05-29 09:05 UTC, sanjay900 commented on bosch_alarm_mode2/const.py
> +    REQUEST_RAW_HISTORY_EVENTS = 0x15
Yeah so the human readable command isn't supported on the solutions series

2023-05-29 09:06 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +                data = data[self._history_len:]
Different models have the history data in different formats, and we need to know how long the event is in order to chunk it up correctly, though we could possibly do that differently

2023-05-29 09:07 UTC, sanjay900 commented on bosch_alarm_mode2/history.py
> +def _get_int16(data, offset=0):
Weirdly, the functions in the panel are big endian, while the stuff in history is little and I'm not really sure why that is

2023-05-29 09:09 UTC, sanjay900 commented on bosch_alarm_mode2/const.py
> +    REQUEST_RAW_HISTORY_EVENTS = 0x15
That's the only real reason I had to do this in the first place unfortunately, would have been nice to just use that command for sure!

2023-05-29 09:11 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +                data = data[self._history_len:]
Though this one gets solved automatically once we turn all this into proper classes I suspect

2023-05-30 00:03 UTC, sanjay900 commented on bosch_alarm_mode2/const.py
> +    REQUEST_RAW_HISTORY_EVENTS = 0x15
Ive changed it up to use 0x63 if its available, otherwise it uses 0x16

2023-05-30 00:32 UTC, sanjay900 commented
Im not sure if there are B or G panels running firmware old enough that they need the history parsing, or if all of them support the human readable events

2023-05-30 05:08 UTC, mag1024 reviewed
Haven't gone through everything in history.py yet, but sending out now to start the conversation about how to best expose the history to HA.

2023-05-30 05:08 UTC, mag1024 commented on bosch_alarm_mode2/history.py
> +        return
I guess this structure works.
It might be a bit more clear if we had a single History class, and gave it a model-specific event parser object.
Up to you.

2023-05-30 05:19 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +
Alternatively, maybe we could create a Device to represent the panel. I think those can have custom info/actions in a burger sub-menu, and we could have one that shows the log. But that (AFAIK) is not accessible within HA programmatically, so it would be for manual inspection only. I guess that could be ok for history. I can't imagine this big blob of text being particularly useful for automations, etc, anyway.

2023-05-30 06:35 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +
Yeah i don't see why one would build automations based on the history anyways, i think that is mostly just something a person would look at

2023-05-30 06:42 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +
hmm, actually, im not sure if devices let you do that

2023-05-30 10:28 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +
Ive just moved it to its own history sensor

2023-05-30 10:28 UTC, sanjay900 commented
> The library _seems_ to work (at least it doesn't throw any errors), but with the integration changes I got this:
> 
> > 2023-05-30 00:21:47.694 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error adding entities for domain alarm_control_panel with platform bosch_alarm
> > Traceback (most recent call last):
> > File "/home/mag/homeassistant/core/homeassistant/helpers/entity_platform.py", line 464, in async_add_entities
> > await asyncio.gather(*tasks)
> > File "/home/mag/homeassistant/core/homeassistant/helpers/entity_platform.py", line 742, in _async_add_entity
> > await entity.add_to_platform_finish()
> > File "/home/mag/homeassistant/core/homeassistant/helpers/entity.py", line 870, in add_to_platform_finish
> > await self.async_added_to_hass()
> > File "/home/mag/homeassistant/core/config/custom_components/bosch_alarm/alarm_control_panel.py", line 122, in async_added_to_hass
> > await self._panel.load_history(start_id, history)
> > File "/home/mag/homeassistant/core/config/custom_components/bosch_alarm/bosch_alarm_mode2/panel.py", line 178, in load_history
> > await self._history._load_history(last_event_id, previous_events)
> > TypeError: object NoneType can't be used in 'await' expression

I have fixed this now

2023-05-30 10:29 UTC, sanjay900 commented on bosch_alarm_mode2/history.py
> +        return
Since its working i don't really want to change it up again

2023-05-31 03:39 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        return self._history.last_event_id
Maybe we can make the history a list of tuples of (event_id, date, description) so that we don't need to keep track of the last_event_id specially?

2023-05-31 03:39 UTC, mag1024 commented on bosch_alarm_mode2/history.py
> +class SolutionAMAXHistory(History):
nit: personally I'm a big fan of this: https://www.approxion.com/capital-offenses-how-to-handle-abbreviations-in-camelcase/

2023-05-31 03:39 UTC, mag1024 commented on bosch_alarm_mode2/history.py
> +        return date + SOLUTION_HISTORY_FORMAT[event_code].format(user=user, param1=first_param, param2=second_param)
nit: line wrap

2023-05-31 03:39 UTC, mag1024 commented on bosch_alarm_mode2/history.py
> +class AMAXHistory(SolutionAMAXHistory):
line break before all classes, please

2023-05-31 03:39 UTC, mag1024 commented on bosch_alarm_mode2/history.py
> +            event = f"{date} {time} | {event}"
Oof, the reuse of events, and the similarity of event and events makes this kinda hard to follow.

2023-05-31 03:49 UTC, mag1024 commented
Long term it's worth studying how the z-wave integration build their devices. They both a have a completely custom statistics popup accessible via the devices' burger menu, and, possibly even more compelling, they emit custom events that get recorded in HA's native Logbook.
![image](https://github.com/mag1024/bosch-alarm-mode2/assets/787978/40c3a8bc-934d-40cc-af57-968f2f316901)

2023-05-31 21:56 UTC, sanjay900 commented
> Long term it's worth studying how the z-wave integration build their devices. They both a have a completely custom statistics popup accessible via the devices' burger menu, and, possibly even more compelling, they emit custom events that get recorded in HA's native Logbook. ![image](https://user-images.githubusercontent.com/787978/242153488-40c3a8bc-934d-40cc-af57-968f2f316901.png)

well now im tempted to see how the hell they do that because it does look a lot nicer. Getting everything in the log book would also be a nice method to go with as well, i just need to work out how the hell that sorta thing is actually done, and im not 100% sure we can do that with custom timestamps for importing the old events

2023-06-09 11:07 UTC, sanjay900 commented
> Long term it's worth studying how the z-wave integration build their devices. They both a have a completely custom statistics popup accessible via the devices' burger menu, and, possibly even more compelling, they emit custom events that get recorded in HA's native Logbook. ![image](https://user-images.githubusercontent.com/787978/242153488-40c3a8bc-934d-40cc-af57-968f2f316901.png)

Turns out this is something extremely specific to Z-Wave, and isn't just something anybody can do, but what i can do is  set up a device anyways, and then tag the history as a DIAGNOSTIC sensor so that it isnt automatically added to panels or voice assistants

2023-06-10 03:36 UTC, mag1024 commented
Ah, that's unfortunate. Thanks for investigating!
Anyway, we can fiddle with exactly how we surface the events in HA after we merge the initial version. The main thing I'd like to address before then is to find a way around having to have an init_history call. It seems to me that the current structure is _too_ influenced by the fact that we currently use a separate sensor, and it is the one persisting the history state, and results in a somewhat strange API for the library.
Can we find a way to persist the the history state (last event id) at the integration level, s.t. it can be read at initialization time, and given to the Panel constructor? Alternatively, we could forego state persistence altogether for now -- just always read the entire history on startup (this would also allow us to remove init_history) -- and add load time optimizations later.

2023-06-10 04:52 UTC, sanjay900 commented
> Ah, that's unfortunate. Thanks for investigating! Anyway, we can fiddle with exactly how we surface the events in HA after we merge the initial version. The main thing I'd like to address before then is to find a way around having to have an init_history call. It seems to me that the current structure is _too_ influenced by the fact that we currently use a separate sensor, and it is the one persisting the history state, and results in a somewhat strange API for the library. Can we find a way to persist the the history state (last event id) at the integration level, s.t. it can be read at initialization time, and given to the Panel constructor? Alternatively, we could forego state persistence altogether for now -- just always read the entire history on startup (this would also allow us to remove init_history) -- and add load time optimizations later.

Ill look into the persistance stuff soon, however i am just going to test what i have with a sol 3000 panel that supports subscriptions, and next week i will be receiving a b series panel as well, so i will test history with both panels and get everything working with the three panels i will have here.

2023-06-15 03:11 UTC, sanjay900 commented
I have now obtained a b series panel

2023-06-15 11:25 UTC, sanjay900 commented
> Ah, that's unfortunate. Thanks for investigating! Anyway, we can fiddle with exactly how we surface the events in HA after we merge the initial version. The main thing I'd like to address before then is to find a way around having to have an init_history call. It seems to me that the current structure is _too_ influenced by the fact that we currently use a separate sensor, and it is the one persisting the history state, and results in a somewhat strange API for the library. Can we find a way to persist the the history state (last event id) at the integration level, s.t. it can be read at initialization time, and given to the Panel constructor? Alternatively, we could forego state persistence altogether for now -- just always read the entire history on startup (this would also allow us to remove init_history) -- and add load time optimizations later.

Alright, ive figured out how to use `homeassistant.helpers.storage.Store` and have now decoupled the history persistance from the entity

2023-06-15 11:36 UTC, sanjay900 commented
Also, now that I'm using developer panels instead of my main house alarm, i ended up setting up a home assistant dev environment. It turns out when you do this, you can easily test both the integration and the module, as you can just clone the integration and symlink it to custom_integrations, and then you can `python -m pip install bosch-alarm-mode2/` and it will install it from the filesystem, and if you then use the "skip pip" option when starting home assistant, it will use the version of the module you just installed, instead of attempting to pull another one.

2023-06-16 02:20 UTC, mag1024 reviewed
Overall looks good, thank you! Only minor comments this time.

2023-06-16 02:20 UTC, mag1024 commented on bosch_alarm_mode2/history.py
> +            return check
probably need a default return here?

2023-06-16 02:20 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +    LOAD_ALL = LOAD_BASIC_INFO | LOAD_ENTITIES | LOAD_STATUS | LOAD_HISTORY
I don't think we need a separate load toggle for history.
The 3 different modes are motivated by 3 specific use case:
1) initial connection at integration setup time creates a scratch Panel to verify that the provided connection information is valid, so it uses the minimal "basic info"
2) when creating a new Panel instance normally, we load everything
3) when re-establishing the connection to the panel after an interruption, we need to catch up on state, so we reload the "state"

Under this classification, history is just a sub-case of "state"

2023-06-16 02:20 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +                await self._load_history()
let's do the init in the in the constructor, without storing previous events in a member
and is there a reason to make the _load_history() conditional?

2023-06-16 02:20 UTC, mag1024 commented on bosch_alarm_mode2/history.py
> +    def _init_history(self, events):
This is called by the Panel, so it should be "public", right? (i.e. remove "_")

2023-06-16 02:20 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +    def history(self):
a return type annotation might be useful here to avoid forcing users of Panel to dig into the implementation of the history class

2023-06-16 02:20 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +            if supports_command_request_history_raw_ext:
self._history_cmd = ... if ... else ... 
might be more idiomatic

2023-06-16 02:20 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        return self._history._parse_subscription_event(data)
This method (correctly) doesn't have the leading _

2023-06-16 02:20 UTC, mag1024 commented on pyproject.toml
> +version = "0.0.0.dev3"
Remember to revert please

2023-06-16 02:31 UTC, mag1024 commented
> I have now obtained a b series panel

Cool! It's very confusing that my panel **B**8512G is part of the G-series. Who came up with this naming??
BTW, is there any chance your Bosch contacts can hook me up with whatever's necessary to run the configuration software for my panel? I've tried to get this to work a while back, and wasn't able to, because I think it requires some kind of a hardware security dongle.

2023-06-16 02:50 UTC, mag1024 commented
> Since you set the device up, i also specified that the history sensor is a diagnostic sensor, and so it gets put into the diagnostic section of the device instead of being listed with the other sensors.

Oh nice. That seems good for now. I randomly met Paulus (the HA founder) the other day, and he mentioned something about how integrations can even have custom dashboards now. I feel like there are a lot of advanced non-documented options for what one can do, so maybe eventually we'll find something better.

2023-06-16 03:00 UTC, sanjay900 commented on bosch_alarm_mode2/panel.py
> +                await self._load_history()
that doesn't work as the history object will change once we know what type of history the panel supports. I suppose this is where your idea of splitting out parsing from the history object would probably help

2023-06-16 03:12 UTC, sanjay900 commented on pyproject.toml
> +version = "0.0.0.dev3"
Ill revert now, i don't actually need to do this sort of thing anymore

2023-06-16 05:20 UTC, sanjay900 commented
> > I have now obtained a b series panel
> 
> Cool! It's very confusing that my panel **B**8512G is part of the G-series. Who came up with this naming?? BTW, is there any chance your Bosch contacts can hook me up with whatever's necessary to run the configuration software for my panel? I've tried to get this to work a while back, and wasn't able to, because I think it requires some kind of a hardware security dongle.

what did it do when you tried to use it? I notice the the guide for the B series panel also mentions the same key, but it isnt necessary, I did however find that when i was configuring it with RPS, it refused to let me do the initial setup (giving me a red X) unless i put in my public IP address, which i then was able to change back to my local one later for testing. You also should be able to just use a usb A to A cable for programming directly as well from what i gather.

2023-06-16 08:09 UTC, sanjay900 commented
> > I have now obtained a b series panel
> 
> Cool! It's very confusing that my panel **B**8512G is part of the G-series. Who came up with this naming?? BTW, is there any chance your Bosch contacts can hook me up with whatever's necessary to run the configuration software for my panel? I've tried to get this to work a while back, and wasn't able to, because I think it requires some kind of a hardware security dongle.

Haha that naming confused the hell out of me too when i was implementing that history stuff, but that reminds me to add the fact that we now know the B5512 works

2023-06-16 10:24 UTC, sanjay900 commented
I have now also been able to confirm that subscription based history events are parsing correctly as well, and i have simplified the parsing of text based events

2023-06-17 01:51 UTC, merged

2023-06-17 01:51 UTC, mag1024 commented
The parser changes look like they worked out great -- thank you!

2023-06-17 01:52 UTC, mag1024 commented
> I did however find that when i was configuring it with RPS, it refused to let me do the initial setup (giving me a red X) unless i put in my public IP address, which i then was able to change back to my local one later for testing.

Ah, that could very well be it! I'll have to try that the next time I get around to playing with it.

2023-06-17 02:55 UTC, mag1024 commented
The history loading is so slow on my panel, that it trips hearbeat and resets the connection, causing it to restart the load 🤦

2023-06-17 03:49 UTC, mag1024 commented
Maybe we should limit it to something reasonable like 1 month of events of backlog -- otherwise it's loading stuff from 2021, which doesn't seem particularly useful.....

2023-06-17 04:06 UTC, sanjay900 commented
Annoyingly, all we can do is specify a event id to start from, there's no way to specify a date specifically.

2023-06-18 02:31 UTC, mag1024 commented
Yeah, I'm in strongly in favor of not adding any parameters that we don't absolutely need, so hardcoding a sane default for the number of events to load sounds pretty reasonable.
In the meantime, I experimented with forcing the use of the binary history format on my panel to see if it's any faster, and found that it totally doesn't work. There are so many errors, that I suspect that there's something totally off with the parsing: either wrong endian-ness, or maybe something off with the byte offsets.
Dropping some sample errors here in case you get around to looking into it before I do: [history-errors.txt](https://github.com/mag1024/bosch-alarm-mode2/files/11780438/history-errors.txt)

2023-06-18 02:42 UTC, mag1024 commented
Oh, yeah, it's totally the endian-ness: switching to BE fixes it. Can you please check if your B-series uses LE or BE in binary mode?

2023-06-18 03:58 UTC, mag1024 commented
BTW, have you looked into Protocol 4 at all? Seems like it basically uses 16 bit lengths, instead of 8 bit, allowing it to return much larger responses -- up to 23 per history response. I tried it out by hacking some stuff in connection.py, and the panel seems to respond with... something. But it doesn't match what we're currently expecting

2023-06-18 04:09 UTC, sanjay900 commented
I didn't really look at the other formats tbh, but tbh I kind of like the idea of just limiting it to 30 responses or so.
I implemented that logic here: https://github.com/mag1024/bosch-alarm-mode2/pull/7