Add a semaphore on some of the memory commands
mag1024/bosch-alarm-mode2 pull request #38
Opened 2024-09-07 03:31 UTC by sanjay900

The solution panels get very confused when you try and send multiple commands that interact with memory, such as `CMD.REQUEST_PANEL_SYSTEM_STATUS` and `CMD.ALARM_MEMORY_DETAIL`.

On my solution 4000, I noted that the second command would just never actually respond, and even worse, the command would then eat the response of the next command that was received, which resulted in it trying to parse responses that weren't valid.

2024-09-07 03:33 UTC, sanjay900 commented
This may potentially help with https://github.com/mag1024/bosch-alarm-homeassistant/issues/32 and https://github.com/mag1024/bosch-alarm-homeassistant/issues/31 as well.

2024-09-07 03:49 UTC, sanjay900 commented
Can confirm this works on the `B5512 (US1B)` as well as the `Solution 4000`. Ill check the AMAX panel and the 3000 as well.

2024-09-07 04:08 UTC, sanjay900 commented
`Solution 3000` works

2024-09-07 08:33 UTC, sanjay900 commented
Seems like the priorities do read correctly from the AMAX panel too, had to remember how to update and configure it

2024-09-08 02:10 UTC, mag1024 commented
I did some testing, and I think I was able to reproduce the problem.
From what I can tell, it doesn't have anything to do with concurrent memory commands per se -- rather, I believe, it is the `output status` command that is busted, and sometimes fails to return any response, causing havoc on response ordering.
Could you please try disabling `_load_output_status`, and seeing if it fixes this problem on Solution panels?

2024-09-08 03:14 UTC, sanjay900 commented
Interesting, I'll give that a go when I get home.

2024-09-08 04:33 UTC, sanjay900 commented
> I did some testing, and I think I was able to reproduce the problem. From what I can tell, it doesn't have anything to do with concurrent memory commands per se -- rather, I believe, it is the `output status` command that is busted, and sometimes fails to return any response, causing havoc on response ordering. Could you please try disabling `_load_output_status`, and seeing if it fixes this problem on Solution panels?

Since I don't have outputs configured on my panel, it would have been exiting that function early, so all my testing was done without that command being involved.

2024-09-08 05:50 UTC, mag1024 commented
I'm basically trying to confirm the theory that this is somehow related to concurrent memory commands.
To do that, I've been running a function like this several times after connect:

```
async def memory_test(self):
    await asyncio.gather(
        self._load_faults(),
        self._load_history(),
        self._load_faults(),
        self._load_history(),
        self._load_faults(),
        self._load_history(),
        self._load_faults(),
        self._load_history(),
        self._get_alarms_for_priority(0x07),
        self._get_alarms_for_priority(0x09),
        self._get_alarms_for_priority(0x0A)
    )
```

I'm also logging the request for each response we process, so I can see if they ever get mismatched.
So far, the only time I've seen it fail -- and for a while I had it failing pretty consistently -- has been when there's also an output status query happening, and it is always the one that drops the response, not any of the memory commands. So it definitely seems buggy, but maybe some other commands are too.

2024-09-08 05:58 UTC, sanjay900 commented
One thing to note is the panels get worse at responding when they are actually armed as well. I know for a fact that the memory related commands especially get a bit whack - commands for history for example just stop working all together when you arm the panel.

2024-09-09 02:59 UTC, mag1024 commented
I did more testing, including while armed, and over 100+ runs, it hasn't failed once without output status fetching -- whereas with it enabled, it seem to fail somewhat regularly.

I pushed the hacky code I'm using for testing to memory_test branch. Could you please give it a shot with your panels?
You can run it in a shell for-loop, because if there is a missing response, the last command will get stuck waiting for a response.

2024-09-09 03:06 UTC, sanjay900 commented
What panel are you testing this with?

2024-09-09 03:08 UTC, sanjay900 commented
It was happening whenever I set the alarm off, and it happened every time on my 4000 before I added that semaphore.

I'll see if that happens with my 3000 as well and run your stress test.

2024-09-09 04:14 UTC, mag1024 commented
I'm testing with my old faithful B8512G.
The reason I'm trying to confirm if there's actually an issue with concurrent memory commands, is that I suspect that while the semaphore happens to help ameliorate the triggering issue, it does so indirectly, and as such will not be reliable.
If the issue is not specific to the memory commands, but rather with the panel being "too loaded" or some such while triggering, and randomly dropping commands, this is probably not the right approach to fixing it.

2024-09-09 04:37 UTC, EHylands commented
Hi @sanjay900 and @mag1024 
Some words for thought.

Had same out of sync and corrupted responses with outputs and alarms details function on Solution panels. 

Mostly appeared when protocol 0x01 function (get outputs states and get alarm details) gets called from async protocol 0x02 before previous command answer has been received. I used Sanjay semaphore solution to fix the issue (1 semaphore shared amongst all protocol 0x01 calls).

Did extensive documentation reading and no information is given regarding commands concurrency nor about any guaranteed response order of arrival.

2024-09-09 04:52 UTC, mag1024 commented
> Did extensive documentation reading and no information is given regarding commands concurrency nor about any guaranteed response order of arrival.

For a streaming protocol like this with no message ids, the _only_ sane behavior is to guarantee order, and responses. If ever the panel needs to drop some messages, it _must_ NACK, or reset the connection. Dropping and/or reordering responses is always a bug in the firmware.

> Mostly appeared when protocol 0x01 function (get outputs states and get alarm details) gets called from async protocol 0x02 before previous command answer has been received. 

Have you tried disabling output polling? AFAICT, their implementation in the firmware is very half-baked. Sanjay already ran into concurrency issues with setting of the outputs, the output ids used in subscription events are unusable, and now it looks like the output get state is prone to getting dropped.

2024-09-09 07:15 UTC, sanjay900 commented
> > Did extensive documentation reading and no information is given regarding commands concurrency nor about any guaranteed response order of arrival.
> 
> For a streaming protocol like this with no message ids, the _only_ sane behavior is to guarantee order, and responses. If ever the panel needs to drop some messages, it _must_ NACK, or reset the connection. Dropping and/or reordering responses is always a bug in the firmware.
> 
> > Mostly appeared when protocol 0x01 function (get outputs states and get alarm details) gets called from async protocol 0x02 before previous command answer has been received.
> 
> Have you tried disabling output polling? AFAICT, their implementation in the firmware is very half-baked. Sanjay already ran into concurrency issues with setting of the outputs, the output ids used in subscription events are unusable, and now it looks like the output get state is prone to getting dropped.

The thing is, it can't just be the output polling since i was running into this problem even without output polling being enabled. It sounds more like we just have to throw a semaphore on all commands, so that we don't ever get in the position where more than one command is on the wire at a time.

2024-09-09 07:28 UTC, sanjay900 commented
> I'm testing with my old faithful B8512G. The reason I'm trying to confirm if there's actually an issue with concurrent memory commands, is that I suspect that while the semaphore happens to help ameliorate the triggering issue, it does so indirectly, and as such will not be reliable. If the issue is not specific to the memory commands, but rather with the panel being "too loaded" or some such while triggering, and randomly dropping commands, this is probably not the right approach to fixing it.

Just using your branch to test, if i run any two commands at the same time with gather, the first one gets a response and the second one doesn't. For me, it just hangs like its waiting for a response that never arrives if i do that.

2024-09-09 07:51 UTC, sanjay900 commented
Oh my god i think this might be what was causing the network module to hang.

2024-09-09 08:01 UTC, sanjay900 commented
Seems that it is only the solution and amax panels that just can't tolerate multiple commands simultaneously like that, the B5512 I have does not seem to care.

2024-09-10 02:44 UTC, mag1024 requested changes
Cool, I like this a lot more, because this feels much more principled than randomly mutexing _some_ commands.
Please update the PR description.

2024-09-10 02:44 UTC, mag1024 commented on bosch_alarm_mode2/connection.py
> +    async def send_command(self, code, data = bytearray()) -> asyncio.Future:
No longer accurate

2024-09-10 02:44 UTC, mag1024 commented on bosch_alarm_mode2/connection.py
> +        self._transmit_semaphore = asyncio.Semaphore(1)
since the critical section includes waiting for the response, not just transmitting the command, `_command_semaphore` might be more appropriate

2024-09-10 02:44 UTC, mag1024 commented on bosch_alarm_mode2/connection.py
> +        self._transmit_semaphore = asyncio.Semaphore(1)
It's really unfortunate to limit all panels to a single in flight command because some older panels can't deal with it. Let's set the limit based on the model. For more capable panels, I think we can set a high limit here, and deal with the triggering issue with a combination of #39, and converting the subscription handlers to schedule followups with a delay.

2024-09-10 02:48 UTC, mag1024 commented
@sanjay900, should we also report the issues with response dropping as bugs to Bosch?
The output implementation in particular seems quite busted -- and it seems that other commands can also be problematic when the panel is loaded, such as with triggering.

2024-09-10 03:00 UTC, sanjay900 commented on bosch_alarm_mode2/connection.py
> +        self._transmit_semaphore = asyncio.Semaphore(1)
Yeah I guess we just have to decide what a reasonable limit is for the b and g panels

2024-09-10 03:01 UTC, sanjay900 commented
> @sanjay900, should we also report the issues with response dropping as bugs to Bosch? The output implementation in particular seems quite busted -- and it seems that other commands can also be problematic when the panel is loaded, such as with triggering.

I've done so already and given them a link to this thread as well

2024-09-10 03:17 UTC, mag1024 commented on bosch_alarm_mode2/connection.py
> +        self._transmit_semaphore = asyncio.Semaphore(1)
Up until now, it has been unlimited so... 10? 100?

2024-09-10 05:26 UTC, mag1024 approved these changes

2024-09-10 05:26 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +        if self.model >= 0xA0:
self.model is a string model descriptor -- this should be `data[0]`

2024-09-10 05:26 UTC, mag1024 commented on bosch_alarm_mode2/connection.py
> +        self._command_semaphore = asyncio.Semaphore(1)
can do `self.set_max_commands_in_flight(1)` instead

2024-09-10 05:30 UTC, merged

2024-09-29 08:35 UTC, sanjay900 commented
@mag1024 Had someone reach out from bosch, sounds like its by design that the protocol only works with one command at a time. Seems like they sort of expect you to use the multiple encapsulation protocol if you want to send more than one command at a time.

2024-09-29 16:13 UTC, mag1024 commented
Well, that's a pretty underwhelming response. Clearly, as indicated by the fact that this work fine of with B/G panels, this is a limitation of the _implementation_, not the the _design_ of the protocol.

Implementing an incoming command queue, up to a reasonable buffer limit, is straightforward. However, even if Bosch is unwilling to do that on their low end panels, there is, in my opinion, no excuse for the failure to NACK dropped command, or, at the barest minimum, clearly documenting the expectations in the protocol spec.