Limit the amount of history pulled back
mag1024/bosch-alarm-mode2 pull request #7
Opened 2023-06-17 05:27 UTC by sanjay900

Instead of pulling the entire panels history back, only load the last 30 events.
Also, update the `_last_msg` when retrieving history, to make sure that loading lots of events at once won't ever cause issues.

2023-06-17 05:38 UTC, sanjay900 commented
@mag1024 Does 30 events sound like a good number, or do you think we would be better with more or less than that?

2023-06-18 04:24 UTC, mag1024 requested changes

2023-06-18 04:24 UTC, mag1024 commented on bosch_alarm_mode2/panel.py
> +                start, count = await self._read_history(start)
Oh heh, the multiple read_history calls in this function make it quite tricky to figure out what's going on.

I think we can push all this inside the history object:
1) if events are empty, return 0xFF as the last_event_id
2) if history gets an empty data event, and there are no events, create a sentinel event at _id - history_read_limit_
3) push parsing of count/start into _parse_polled_events_, and have it return a bool to indicate if the load loop should continue -- this way we can avoid exiting the loop after 2

2023-06-18 04:26 UTC, sanjay900 commented
Also can confirm, the endinaness fix works on my b series panel as well

2023-06-19 03:19 UTC, closed without merging